services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: pizza_db
      POSTGRES_USER: pizza_user
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5433:5432"

  backend:
    build:
      context: ./backend
    container_name: django_backend
    environment:
      DEBUG: 'True'
      SECRET_KEY: 'django-insecure-_(n$pz7r65uofrcmmbm(#lscmqtbs4!h=%rlm5qpke)cjs8w91'
      DJANGO_APP_FRONTEND_URL: 'http://localhost:3000'
      ALLOWED_HOSTS: 'localhost'
      DATABASE_URL: 'postgres://pizza_user:yourpassword@db:5432/pizza_db'  # Docker-specific setting
    ports:
      - "8000:8000"
    depends_on:
      - db
